# Generated by Django 5.2.5 on 2025-11-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('location', models.CharField(help_text='Shelf or warehouse location', max_length=100)),
                ('supplier', models.CharField(help_text='Supplier info (replace with FK when Supplier model is ready)', max_length=100)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='phones.phone')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
