# Generated by Django 5.2.8 on 2025-11-29 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('RESTOCK', 'Restock'), ('CORRECTION', 'Correction'), ('INITIAL', 'Initial Stock')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock History',
                'ordering': ['-created_at'],
            },
        ),
    ]
