# Generated by Django 5.2.8 on 2026-01-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder_amount_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
