# Generated by Django 5.2.8 on 2026-02-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_purchaseorderitem_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='Main Warehouse', help_text='Shelf or warehouse location', max_length=100),
        ),
    ]
