# Generated by Django 5.2.5 on 2025-11-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Google', 'Google'), ('Huawei', 'Huawei'), ('Other', 'Other')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage', models.CharField(help_text='e.g., 128GB, 256GB', max_length=50)),
                ('ram', models.CharField(help_text='e.g., 4GB, 8GB', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('IMEI', models.CharField(help_text='Unique identifier for each unit', max_length=15, unique=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost price for profit calculation', max_digits=10)),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['-created_at'],
            },
        ),
    ]
