# Generated by Django 5.2.8 on 2025-11-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Google', 'Google'), ('Huawei', 'Huawei'), ('Other', 'Other')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['brand'], name='phone_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['model'], name='phone_model_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['price'], name='phone_price_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['brand', 'model'], name='phone_brand_model_idx'),
        ),
    ]
