# Generated by Django 5.2.8 on 2025-11-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_brand_alter_phone_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, help_text='Phone image', null=True, upload_to='phones/'),
        ),
    ]
