# Generated by Django 5.2.8 on 2025-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='IMEI',
            field=models.CharField(blank=True, help_text='15-digit IMEI unique identifier (optional)', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Google', 'Google'), ('Huawei', 'Huawei'), ('Other', 'Other')], db_index=True, help_text='Phone manufacturer brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(help_text='Phone color variant', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], help_text='Product condition status', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed product description', null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image file', null=True, upload_to='phones/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(db_index=True, help_text='Phone model name', max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Selling price in local currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(help_text='RAM capacity (e.g., 4GB, 8GB)', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(help_text='Storage capacity (e.g., 128GB, 256GB)', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
    ]
