# Generated by Django 5.2.8 on 2025-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_imei_alter_phone_brand_alter_phone_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='product_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Case', 'Phone Case'), ('Charger', 'Charger'), ('Cable', 'Cable'), ('Screen Protector', 'Screen Protector'), ('Headphones', 'Headphones'), ('Power Bank', 'Power Bank'), ('Memory Card', 'Memory Card'), ('Adapter', 'Adapter'), ('Holder', 'Phone Holder'), ('Other', 'Other Accessory')], db_index=True, default='Phone', help_text='Type of product (Phone, Case, Charger, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='IMEI',
            field=models.CharField(blank=True, help_text='15-digit IMEI unique identifier for phones (optional for accessories)', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Google', 'Google'), ('Huawei', 'Huawei'), ('Anker', 'Anker'), ('Belkin', 'Belkin'), ('Spigen', 'Spigen'), ('OtterBox', 'OtterBox'), ('Generic', 'Generic'), ('Other', 'Other')], db_index=True, help_text='Phone manufacturer brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.CharField(help_text='Product color variant', max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(blank=True, help_text='RAM capacity for phones (e.g., 4GB, 8GB) - optional for accessories', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(blank=True, help_text='Storage capacity for phones (e.g., 128GB, 256GB) - optional for accessories', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['product_type'], name='phone_prodtype_idx'),
        ),
    ]
