# Generated by Django 5.2.8 on 2025-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_phone_product_type_alter_phone_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='product_type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Case', 'Phone Case'), ('Charger', 'Charger'), ('Cable', 'Cable'), ('Screen Protector', 'Screen Protector'), ('Headphones', 'Headphones'), ('Earphones', 'Earphones'), ('Power Bank', 'Power Bank'), ('Memory Card', 'Memory Card'), ('Adapter', 'Adapter'), ('Holder', 'Phone Holder'), ('Other', 'Other Accessory')], db_index=True, default='Phone', help_text='Type of product (Phone, Case, Charger, etc.)', max_length=50),
        ),
    ]
