# Generated by Django 5.2.8 on 2026-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_alter_phone_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='battery_percentage',
            field=models.IntegerField(blank=True, help_text='Battery percentage/health (especially for Apple devices)', null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='IMEI',
            field=models.CharField(blank=True, help_text='15-digit IMEI unique identifier for phones (optional)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used'), ('Defective', 'Defective')], help_text='Product condition status', max_length=20),
        ),
    ]
