# Generated by Django 5.2.8 on 2026-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_phone_battery_percentage_alter_phone_imei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='barcode',
            field=models.CharField(blank=True, help_text='Professional unique barcode (e.g., PM-000123)', max_length=50, null=True, unique=True),
        ),
    ]
