# Generated by Django 5.2.8 on 2026-02-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_location'),
        ('phones', '0008_phone_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier of this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='inventory.supplier'),
        ),
    ]
