# Generated by Django 5.2.8 on 2026-02-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_phone_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image_url',
            field=models.URLField(blank=True, help_text='External product image URL', max_length=500, null=True),
        ),
    ]
