# Generated by Django 5.2.8 on 2026-04-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_add_laptop_fields'),
        ('phones', '0010_phone_image_url'),
    ]

    operations = [
    ]
