# Generated by Django 5.2.8 on 2026-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_location'),
        ('phones', '0012_alter_phone_product_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['IMEI'], name='phone_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['barcode'], name='phone_barcode_idx'),
        ),
    ]
