# Generated by Django 5.2.8 on 2025-11-29 21:20

import apps.shop.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shop/company name', max_length=255)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number format is invalid', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('address_line_1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Additional address information (optional)', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province (optional)', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code (optional)', max_length=20, null=True)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol (e.g., $, €, £)', max_length=5, validators=[apps.shop.models.validate_currency_symbol])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax rate as percentage (e.g., 8.25 for 8.25%)', max_digits=5)),
                ('logo', models.ImageField(blank=True, help_text='Shop logo for invoices and reports', null=True, upload_to='shop_logos/')),
                ('invoice_footer', models.TextField(blank=True, help_text='Footer text for invoices', null=True)),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shop Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
