# Generated by Django 5.2.8 on 2025-12-12 15:00

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Algeria', help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='currency_symbol',
            field=models.CharField(default='DZD', help_text='Currency symbol (e.g., $, €, £, DZD)', max_length=5, validators=[apps.shop.models.validate_currency_symbol]),
        ),
    ]
