# Generated by Django 5.2.8 on 2026-01-23 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_country_alter_shop_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number format is invalid. Use 10 digits (0550660064) or international format (+213550660064)', regex='^(\\+?[\\d\\s\\-\\(\\)]{9,20}|0[\\d]{9})$')]),
        ),
    ]
