# Generated by Django 5.2.8 on 2026-01-26 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_update_phone_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram handle (e.g., @shopname)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email (optional)', max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
