# Generated by Django 5.2.8 on 2026-02-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_instagram_handle_alter_shop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='barcode_label_height',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Label height in mm', max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='barcode_label_width',
            field=models.DecimalField(decimal_places=2, default=45.0, help_text='Label width in mm', max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='barcode_orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', help_text='Print orientation', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='barcode_printer_name',
            field=models.CharField(default='Xprinter XP-233B', help_text='Default barcode printer name', max_length=255),
        ),
    ]
