# Generated by Django 5.2.5 on 2025-11-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied to sale', max_digits=6)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0.0, help_text='Profit margin for this sale', max_digits=10)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='phones.phone')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
