# Generated by Django 5.2.8 on 2025-11-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_brand_alter_phone_model_and_more'),
        ('sales', '0002_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sale_sale_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer_name'], name='sale_customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['phone', 'sale_date'], name='sale_phone_date_idx'),
        ),
    ]
