# Generated by Django 5.2.8 on 2026-01-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check'), ('Mobile Wallet', 'Mobile Wallet'), ('Other', 'Other')], default='Cash', max_length=50),
        ),
    ]
