# Generated by Django 5.2.8 on 2026-01-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='trade_in_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value of traded-in device', max_digits=10),
        ),
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('imei', models.CharField(blank=True, max_length=15, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], default='Used', max_length=50)),
                ('trade_in_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_in', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Trade-in',
                'verbose_name_plural': 'Trade-ins',
            },
        ),
    ]
