# Generated by Django 5.2.8 on 2026-01-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_customer_balance_sale_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradein',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used'), ('Defective', 'Defective')], default='Used', max_length=50),
        ),
    ]
