# Generated by Django 5.2.8 on 2026-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='profit_impact',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit lost by this return', max_digits=10),
        ),
    ]
