# Generated by Django 5.2.8 on 2026-01-17 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_phone_barcode'),
        ('sales', '0013_salereturn_profit_impact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Product Return',
                'verbose_name_plural': 'Product Returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded for this item', max_digits=10)),
                ('profit_impact', models.DecimalField(decimal_places=2, default=0.0, help_text='Impact on profit (usually negative)', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.phone')),
                ('product_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.productreturn')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Product Return Item',
                'verbose_name_plural': 'Product Return Items',
            },
        ),
        migrations.DeleteModel(
            name='SaleReturn',
        ),
    ]
