# Generated by Django 5.2.8 on 2026-01-17 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_productreturn_productreturnitem_delete_salereturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreturnitem',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.saleitem'),
        ),
    ]
