# Generated by Django 5.2.8 on 2026-01-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='warranty_duration',
            field=models.CharField(blank=True, help_text='Warranty duration (e.g., 12 months)', max_length=100, null=True),
        ),
    ]
