# Generated by Django 5.2.8 on 2026-01-31 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_phone_barcode'),
        ('sales', '0018_sale_warranty_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product_name_at_sale',
            field=models.CharField(blank=True, help_text='Caches product name for single-item sales', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_name_at_sale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productreturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.phone'),
        ),
    ]
