# Generated by Django 5.2.8 on 2026-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_sale_product_name_at_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product_data_snapshot',
            field=models.JSONField(blank=True, help_text='Stores product data before deletion for refund restoration', null=True),
        ),
    ]
