# Generated by Django 5.2.8 on 2026-03-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0010_phone_image_url'),
        ('sales', '0021_backfill_product_data_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradein',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trade-in', 'verbose_name_plural': 'Trade-ins'},
        ),
        migrations.AddField(
            model_name='tradein',
            name='color',
            field=models.CharField(blank=True, default='Non spécifié', help_text='Color of the traded-in device', max_length=50),
        ),
        migrations.AddField(
            model_name='tradein',
            name='received_phone',
            field=models.OneToOneField(blank=True, help_text='The phone record added to inventory from this trade-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_received', to='phones.phone'),
        ),
        migrations.AddField(
            model_name='tradein',
            name='storage',
            field=models.CharField(blank=True, help_text='Storage capacity of the traded-in device', max_length=50, null=True),
        ),
    ]
